name: NetBase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore "TryActions\TryActions.sln"
    
    - name: Build solution
      run: dotnet build "TryActions\TryActions.sln"

    - name: Test
      run: dotnet test "TryActions\TryActions.sln" --no-build --verbosity normal  
